services:
  userform:
    image: userform:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - userform-network

networks:
  userform-network:
    driver: bridge
