name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t secure-userform:latest .

      - name: Run Docker container with Spring profile
        run: |
          docker run -d --rm \
            -e SPRING_PROFILES_ACTIVE=prod \
            -p 8080:8080 \
            --name secure-userform-container \
            secure-userform:latest

      - name: Wait for the application to start
        run: |
          echo "Waiting for the app to be ready..."
          sleep 20

      - name: Verify the application is running
        run: curl --fail http://localhost:8080/actuator/health || exit 1

      - name: Print health check result
        run: curl http://localhost:8080/actuator/health
